FROM python:3.9-slim

# 安装最小必要的依赖
RUN apt-get update && \
    apt-get install -y --no-install-recommends iputils-ping && \
    pip install --no-cache-dir resend && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./app /app

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
